create or replace view BRONZE_DATA.TCM_BRONZE.ALL_SALES_HIST(
	"OrderID",
	"LineNumber",
	"Ordered Date",
	"Stock Flag",
	"InvoiceID",
	"Freight_Cost",
	"Sales_Tax",
	"Customer Name",
	"Customer ID",
	"Customer Type",
	"CUST/GROUP CODE",
	"CUST/GROUP NAME",
	"Sold to Address",
	"Sold to City",
	"Sold to State",
	"Sold to Zip Code",
	"Sold to Country",
	"Customer Attribute Flag",
	"Ship to Address",
	"Ship to City",
	"Ship to State",
	"Ship to Zip Code",
	"Ship to Customer Name",
	"Ship to #",
	"Ship to Country",
	"TCM Sales Rep ID",
	"Product ID/SKU",
	"Product Description",
	"COST CATEGORY ID",
	"COST CAT DESCR",
	"PRODUCT CATEGORY/VERTICAL",
	"PRDT CAT DESCR",
	"VERTICAL (Calc)",
	"CATEGORY (Calc)",
	"Product Name/Parent ID",
	"PARENT DESCRIPTION",
	"ATTR (SKU) CERT_NUM",
	"ATTR (SKU) COLOR",
	"ATTR (SKU) SIZE",
	"ATTR (SKU) LENGTH",
	"ATTR (SKU) TARIFF_CODE",
	"ATTR (SKU) UPC_CODE",
	"ATTR (SKU) PFAS",
	"ATTR (PAR) BERRY",
	"ATTR (PAR) CARE",
	"ATTR (PAR) HEAT TRANSFER",
	"ATTR (PAR) OTHER",
	"ATTR (PAR) PAD PRINT",
	"ATTR (PAR) PRODUCT CAT",
	"ATTR (PAR) PRODUCT TYPE",
	"ATTR (PAR) TRACKING",
	"ATTR (PAR) Z_BRAND",
	"ATTR (PAR) Z_CATEGORY",
	"ATTR (PAR) Z_GENDER",
	"ATTR (PAR) Z_VERTICAL",
	"PROP 65",
	"INVOICE DATE",
	"ALT_KEY",
    "Child Item Status",
    "Parent Item Status",
	"Reorder Level",
    "Sales Transaction Line ID",
	"Promise Date",
	"Unit Quantity",
	"Total Price",
	"Unit Cost",
	"Sales Rep Name",
	"ID_LOC",
	"LOC DESCR",
	"CALENDAR DATE",
	"Booking Type Table"
) as
-- ================SELECT Statement ========================
SELECT
    sls."OrderID" AS "OrderID",
    sls."LineNumber" as "LineNumber",
    sls."Ordered Date" as "Ordered Date",
    sls."Stock Flag" as "Stock Flag",
    sls."InvoiceID" as "InvoiceID",
    sls."Freight_Cost" as "Freight_Cost",
    sls."Sales_Tax" as "Sales_Tax",
    st.name_cust AS "Customer Name",
    st.id_cust AS "Customer ID",
    st.code_cust AS "Customer Type",
    COALESCE(gc.group_code, st.id_cust) AS "CUST/GROUP CODE",
    COALESCE(gc.group_name, st.name_cust) AS "CUST/GROUP NAME",
    st.ADDR_CUST_2 AS "Sold to Address",
    st.city AS "Sold to City",
    st.id_st AS "Sold to State",
    st.ZIP AS "Sold to Zip Code",
    st.country AS "Sold to Country",
    st.code_user_2_ar as "Customer Attribute Flag",
    sls."Ship to Address" AS "Ship to Address",
    sls."Ship to City" AS "Ship to City",
    sls."Ship to State" AS "Ship to State",
    sls."Ship to Zip Code" AS "Ship to Zip Code",
    cst.name_cust AS "Ship to Customer Name",
    sls.seq_shipto AS "Ship to #",
    sls."Ship to Country" AS "Ship to Country",
    sls."Sales Rep ID" as "TCM Sales Rep ID",
    sls."Product ID/SKU" AS "Product ID/SKU",
    mpt."Product Description",
    mpt."COST CATEGORY ID",
    COALESCE(mpt."COST CAT DESCR", 'INVALID COST CATEGORY') AS "COST CAT DESCR",
    mpt."PRODUCT CATEGORY/VERTICAL",
    COALESCE(mpt."PRDT CAT DESCR", 'INVALID PRODUCT CATEGORY') AS "PRDT CAT DESCR",
    mpt."VERTICAL (Calc)",
    mpt."CATEGORY (Calc)",
    mpt."Product Name/Parent ID",
    COALESCE(mpt."PARENT DESCRIPTION", 'MISSING DESCRIPTION - UPDATE TCM') AS "PARENT DESCRIPTION",
    mpt."ATTR (SKU) CERT_NUM",
    mpt."ATTR (SKU) COLOR",
    mpt."ATTR (SKU) SIZE",
    mpt."ATTR (SKU) LENGTH",
    mpt."ATTR (SKU) TARIFF_CODE",
    mpt."ATTR (SKU) UPC_CODE",
    mpt."ATTR (SKU) PFAS",
    mpt."ATTR (PAR) BERRY",
    mpt."ATTR (PAR) CARE",
    mpt."ATTR (PAR) HEAT TRANSFER",
    mpt."ATTR (PAR) OTHER",
    mpt."ATTR (PAR) PAD PRINT",
    mpt."ATTR (PAR) PRODUCT CAT",
    mpt."ATTR (PAR) PRODUCT TYPE",
    mpt."ATTR (PAR) TRACKING",
    mpt."ATTR (PAR) Z_BRAND",
    mpt."ATTR (PAR) Z_CATEGORY",
    mpt."ATTR (PAR) Z_GENDER",
    mpt."ATTR (PAR) Z_VERTICAL",
    mpt."PROP 65",
    sls."INVOICE DATE" AS "INVOICE DATE",
    mpt."ALT_KEY",
    mpt."Child Item Status",
    mpt."Parent Item Status",
    r.level_rop AS "Reorder Level",
    sls."LineNumber" AS "Sales Transaction Line ID",
    sls."Promise Date" AS "Promise Date",
    sls."Unit Quantity" AS "Unit Quantity",
    sls."Total Price" AS "Total Price",
    sls."Unit Cost" AS "Unit Cost",
    sr.name_slsrep AS "Sales Rep Name",
    sls.id_loc AS "ID_LOC",
    sls.id_loc || ' - ' || tl.DESCR AS "LOC DESCR",
    sls."Calendar Date" AS "CALENDAR DATE",
    sls."Booking Type Table" as "Booking Type Table"
FROM "BRONZE_DATA"."TCM_BRONZE"."SALES_TABLE" sls
left join SILVER_DATA.TCM_SILVER.MASTER_PRODUCT_TABLE mpt on sls."Product ID/SKU" = mpt."Product ID/SKU"
left join "BRONZE_DATA"."TCM_BRONZE"."TABLES_LOC_Bronze" tl on sls.id_loc = tl.id_loc
left join "BRONZE_DATA"."TCM_BRONZE"."TABLES_SLSREP_Bronze" sr on ltrim(sls."Sales Rep ID") = ltrim(sr.id_slsrep)

left join (
    SELECT 
        id_item,
        id_loc_home,
        level_rop,
        ROW_NUMBER() OVER (PARTITION BY id_item ORDER BY "rowid" DESC) as rn
    FROM "BRONZE_DATA"."TCM_BRONZE"."ITMMAS_REORD_Bronze"
) r on sls."Product ID/SKU" = r.id_item and sls.id_loc = r.id_loc_home and r.rn = 1
left join "BRONZE_DATA"."TCM_BRONZE"."CUSMAS_SHIPTO_Bronze" cst on sls."Customer ID" = cst.id_cust and sls.seq_shipto = cst.seq_shipto
left join "BRONZE_DATA"."TCM_BRONZE"."CUSMAS_SOLDTO_Bronze" st on ltrim(sls."Customer ID") = ltrim(st.id_cust)
left join "BRONZE_DATA"."TCM_BRONZE"."CUST_GROUP_CODE_Bronze" gc on st.code_user_3_ar = gc.group_code
WHERE sls."INVOICE DATE" > '1/1/2014' AND st.CODE_CUST <> 'IC';


describe table "BRONZE_DATA"."TCM_BRONZE"."ALL_SALES_HIST"; -- 69 columns

describe table "BRONZE_DATA"."TCM_BRONZE"."INVOICE_HIST_VIEW_2"; -- 71 columns
select count(*) from "BRONZE_DATA"."TCM_BRONZE"."ALL_SALES_HIST";

select * from "BRONZE_DATA"."TCM_BRONZE"."ALL_SALES_HIST" limit 100;