create or replace view BRONZE_DATA.TCM_BRONZE.INVOICE_HIST_VIEW_5(
	"OrderID",
	"LineNumber",
	"Ordered Date",
	"Stock Flag",
	"InvoiceID",
	"Freight_Cost",
	"Sales_Tax",
	"Customer Name",
	"Customer ID",
	"Customer Type",
	"CUST/GROUP CODE",
	"CUST/GROUP NAME",
	"Sold to Address",
	"Sold to City",
	"Sold to State",
	"Sold to Zip Code",
	"Sold to Country",
	"Customer Attribute Flag",
	"Ship to Address",
	"Ship to City",
	"Ship to State",
	"Ship to Zip Code",
	"Ship to Customer Name",
	"Ship to #",
	"Ship to Country",
	"TCM Sales Rep ID",
	"Product ID/SKU",
	"Product Description",
	"COST CATEGORY ID",
	"COST CAT DESCR",
	"PRODUCT CATEGORY/VERTICAL",
	"PRDT CAT DESCR",
	"VERTICAL (Calc)",
	"CATEGORY (Calc)",
	"Product Name/Parent ID",
	"PARENT DESCRIPTION",
	"ATTR (SKU) CERT_NUM",
	"ATTR (SKU) COLOR",
	"ATTR (SKU) SIZE",
	"ATTR (SKU) LENGTH",
	"ATTR (SKU) TARIFF_CODE",
	"ATTR (SKU) UPC_CODE",
	"ATTR (SKU) PFAS",
	"ATTR (PAR) BERRY",
	"ATTR (PAR) CARE",
	"ATTR (PAR) HEAT TRANSFER",
	"ATTR (PAR) OTHER",
	"ATTR (PAR) PAD PRINT",
	"ATTR (PAR) PRODUCT CAT",
	"ATTR (PAR) PRODUCT TYPE",
	"ATTR (PAR) TRACKING",
	"ATTR (PAR) Z_BRAND",
	"ATTR (PAR) Z_CATEGORY",
	"ATTR (PAR) Z_GENDER",
	"ATTR (PAR) Z_VERTICAL",
	"PROP 65",
	"INVOICE DATE",
	ALT_KEY,
	"Reorder Level",
	SEQ_SHIPTO,
	"Promise Date",
	"Quantity Shipped",
	"Total Price",
	"Unit Cost",
	"Sales Rep ID",
	"Sales Rep Name",
	"Sales transaction line ID",
	ID_LOC,
	"LOC DESCR",
	"CALENDAR DATE",
	"Booking Type Table"
) as
-- ================SELECT Statement ========================
SELECT
    lh.id_ord AS "OrderID",
    lh.seq_line_ord as "LineNumber",
    lh.date_book_last as "Ordered Date",
    lh.FLAG_STK as"Stock Flag",
    lh.ID_INVC as "InvoiceID",
    hh.amt_frt as "Freight_Cost",
    hh.tax_sls as "Sales_Tax",
    st.name_cust AS "Customer Name",
    st.id_cust AS "Customer ID",
    st.code_cust AS "Customer Type",
    COALESCE(gc.group_code, st.id_cust) AS "CUST/GROUP CODE",
    COALESCE(gc.group_name, st.name_cust) AS "CUST/GROUP NAME",
    st.ADDR_CUST_2 AS "Sold to Address",
    st.city AS "Sold to City",
    st.id_st AS "Sold to State",
    st.ZIP AS "Sold to Zip Code",
    st.country AS "Sold to Country",
    st.code_user_2_ar as "Customer Attribute Flag",
    hh.addr_2 AS "Ship to Address",
    hh.city AS "Ship to City",
    hh.id_st AS "Ship to State",
    hh.zip AS "Ship to Zip Code",
    hh.name_cust_shipto AS "Ship to Customer Name",
    hh.seq_shipto AS "Ship to #",
    hh.country AS "Ship to Country",
    hh.id_slsrep_1 as "TCM Sales Rep ID",
    lh.id_item AS "Product ID/SKU",
    mpt."Product Description",
    mpt."COST CATEGORY ID",
    COALESCE(mpt."COST CAT DESCR", 'INVALID COST CATEGORY') AS "COST CAT DESCR",
    mpt."PRODUCT CATEGORY/VERTICAL",
    COALESCE(mpt."PRDT CAT DESCR", 'INVALID PRODUCT CATEGORY') AS "PRDT CAT DESCR",
    mpt."VERTICAL (Calc)",
    mpt."CATEGORY (Calc)",
    mpt."Product Name/Parent ID",
    COALESCE(mpt."PARENT DESCRIPTION", 'MISSING DESCRIPTION - UPDATE TCM') AS "PARENT DESCRIPTION",
    mpt."ATTR (SKU) CERT_NUM",
    mpt."ATTR (SKU) COLOR",
    mpt."ATTR (SKU) SIZE",
    mpt."ATTR (SKU) LENGTH",
    mpt."ATTR (SKU) TARIFF_CODE",
    mpt."ATTR (SKU) UPC_CODE",
    mpt."ATTR (SKU) PFAS",
    mpt."ATTR (PAR) BERRY",
    mpt."ATTR (PAR) CARE",
    mpt."ATTR (PAR) HEAT TRANSFER",
    mpt."ATTR (PAR) OTHER",
    mpt."ATTR (PAR) PAD PRINT",
    mpt."ATTR (PAR) PRODUCT CAT",
    mpt."ATTR (PAR) PRODUCT TYPE",
    mpt."ATTR (PAR) TRACKING",
    mpt."ATTR (PAR) Z_BRAND",
    mpt."ATTR (PAR) Z_CATEGORY",
    mpt."ATTR (PAR) Z_GENDER",
    mpt."ATTR (PAR) Z_VERTICAL",
    mpt."PROP 65",
    lh.date_invc AS "INVOICE DATE",
    mpt."ALT_KEY",
    r.level_rop AS "Reorder Level",
    hh.seq_shipto as "SEQ_SHIPTO",
    lh.date_prom AS "Promise Date",
    lh.qty_ship AS "Quantity Shipped",
    lh.price_net AS "Total Price",
    CAST(RIGHT(lh.cost_unit_vp,10) AS DECIMAL)/10000 AS "Unit Cost",
    hh.id_slsrep_1 AS "Sales Rep ID",
    sr.name_slsrep AS "Sales Rep Name",
    lh.seq_line_ord AS "Sales transaction line ID",
    lh.id_loc AS "ID_LOC",
    lh.id_loc || ' - ' || tl.DESCR AS "LOC DESCR",
    lh.date_invc AS "CALENDAR DATE",
    'Shipped' as "Booking Type Table"
FROM "BRONZE_DATA"."TCM_BRONZE"."CP_INVLIN_HIST_Bronze" lh
left join SILVER_DATA.TCM_SILVER.MASTER_PRODUCT_TABLE_2 mpt on lh.id_item = mpt."Product ID/SKU"
left join "BRONZE_DATA"."TCM_BRONZE"."TABLES_LOC_Bronze" tl on lh.id_loc = tl.id_loc
left join "BRONZE_DATA"."TCM_BRONZE"."CP_INVHDR_HIST_Bronze" hh on lh.id_invc = hh.id_invc
left join "BRONZE_DATA"."TCM_BRONZE"."TABLES_SLSREP_Bronze" sr on ltrim(hh.id_slsrep_1) = ltrim(sr.id_slsrep)
left join "BRONZE_DATA"."TCM_BRONZE"."ITMMAS_REORD_Bronze" r on lh.id_item = r.id_item and lh.id_loc = r.id_loc_home
left join "BRONZE_DATA"."TCM_BRONZE"."CUSMAS_SOLDTO_Bronze" st on ltrim(lh.id_cust_soldto) = ltrim(st.id_cust)
left join "BRONZE_DATA"."TCM_BRONZE"."CUST_GROUP_CODE_Bronze" gc on st.code_user_3_ar = gc.group_code
WHERE lh.date_invc > '1/1/2014' AND st.CODE_CUST NOT IN ('IC');