-- check the total number of open orders and total number of line items 
-- Master SILVER_DATA.TCM_SILVER.MASTER_ORDERS_TABLE
SELECT
    COUNT(DISTINCT Mo.ID_ORD) AS TOTAL_ORDERS,
    COUNT(*) AS TOTAL_LINE_ITEMS
FROM SILVER_DATA.TCM_SILVER.MASTER_ORDERS_TABLE Mo
LEFT JOIN SILVER_DATA.TCM_SILVER.MASTER_SHIPMENT_TABLE s 
	ON Mo.ID_ORD = s.ID_ORD 
		AND Mo.SEQ_LINE_ORD=s.SEQ_LINE_ORD 
		AND TRIM(Mo.ID_LOC) = TRIM(s.ID_LOC) 

WHERE Mo.ORD_DATE_CREATED BETWEEN '2026-03-01'::DATE AND '2026-03-31'::DATE
AND Mo.DATE_PROM BETWEEN '2026-03-01'::DATE AND '2026-12-31'::DATE
AND Mo.ID_LOC = '10'
AND (s.ID_SHIP is NULL OR s.QTY_SHIP < Mo.QTY_OPEN)
-- AND Mo.HDR_SOURCE_TABLE = 'ACTIVE'
AND Mo.LIN_SOURCE_TABLE = 'ACTIVE'

AND QTY_OPEN > 0
AND QTY_OPEN <> QTY_SHIP_TOTAL



LEFT JOIN
	(Select id_item, qty_onhd 
		from
		nsa.itmmas_loc 
	where id_loc = 'INTR'
	and qty_onhd <>0) ic
	on ol.id_item = ic.id_item