create or replace view SILVER_DATA.TCM_SILVER.WORK_CENTER_MINUTES_EMPLOYEE_SUMMARY(
	WORK_CENTER,
	WORK_CENTER_LOCATION,
	SUM_ACTUAL_MINS,
	SUM_EARNED_MINS,
	SUM_AVAIL_MINS,
	SUM_INDIR_MINS,
	SUM_SAMPLE_MINS,
	EMPLOYEE_LOCATION,
	WORK_CENTER_DESCRIPTION,
	FIRST_SHIFT_FT,
	SECOND_SHIFT_FT,
	SECOND_SHIFT_PT,
	INACTIVE,
	FIRST_SHIFT_FT_EMPLOYEES,
	SECOND_SHIFT_FT_EMPLOYEES,
	SECOND_SHIFT_PT_EMPLOYEES,
	FIRST_SHIFT_TEAMS,
	SECOND_SHIFT_TEAMS
) as
SELECT
    wcms.*,

    wces.EMPLOYEE_LOCATION,
    wces.WORK_CENTER_DESCRIPTION,
    wces.FIRST_SHIFT_FT,
    wces.SECOND_SHIFT_FT,
    wces.SECOND_SHIFT_PT,
    wces.INACTIVE,
    wces.FIRST_SHIFT_FT_EMPLOYEES,
    wces.SECOND_SHIFT_FT_EMPLOYEES,
    wces.SECOND_SHIFT_PT_EMPLOYEES,
    wces.FIRST_SHIFT_TEAMS,
    wces.SECOND_SHIFT_TEAMS

FROM SILVER_DATA.TCM_SILVER.WORK_CENTER_MINUTES_SUMMARY wcms
LEFT JOIN SILVER_DATA.TCM_SILVER.WORK_CENTER_EMPLOYEE_SUMMARY wces
    ON wcms.WORK_CENTER = wces.WORK_CENTER
    and wcms.work_center_location = wces.employee_location;